-- Indian states (28) and union territories (8) — reference data for dropdowns.
-- Idempotent: safe to re-run if state_name already exists (INSERT IGNORE).

INSERT IGNORE INTO indian_states (id, state_name, is_active) VALUES
(UUID(), 'Andhra Pradesh', 1),
(UUID(), 'Arunachal Pradesh', 1),
(UUID(), 'Assam', 1),
(UUID(), 'Bihar', 1),
(UUID(), 'Chhattisgarh', 1),
(UUID(), 'Goa', 1),
(UUID(), 'Gujarat', 1),
(UUID(), 'Haryana', 1),
(UUID(), 'Himachal Pradesh', 1),
(UUID(), 'Jharkhand', 1),
(UUID(), 'Karnataka', 1),
(UUID(), 'Kerala', 1),
(UUID(), 'Madhya Pradesh', 1),
(UUID(), 'Maharashtra', 1),
(UUID(), 'Manipur', 1),
(UUID(), 'Meghalaya', 1),
(UUID(), 'Mizoram', 1),
(UUID(), 'Nagaland', 1),
(UUID(), 'Odisha', 1),
(UUID(), 'Punjab', 1),
(UUID(), 'Rajasthan', 1),
(UUID(), 'Sikkim', 1),
(UUID(), 'Tamil Nadu', 1),
(UUID(), 'Telangana', 1),
(UUID(), 'Tripura', 1),
(UUID(), 'Uttar Pradesh', 1),
(UUID(), 'Uttarakhand', 1),
(UUID(), 'West Bengal', 1),
(UUID(), 'Andaman and Nicobar Islands', 1),
(UUID(), 'Chandigarh', 1),
(UUID(), 'Dadra and Nagar Haveli and Daman and Diu', 1),
(UUID(), 'Delhi', 1),
(UUID(), 'Jammu and Kashmir', 1),
(UUID(), 'Ladakh', 1),
(UUID(), 'Lakshadweep', 1),
(UUID(), 'Puducherry', 1);
