-- Migration to create customer_registrations table for replacing Supabase functionality
CREATE TABLE IF NOT EXISTS customer_registrations (
  id CHAR(36) NOT NULL,
  email VARCHAR(320) NOT NULL,
  full_name VARCHAR(255) NULL,
  phone VARCHAR(32) NULL,
  oauth_provider VARCHAR(32) DEFAULT 'email',
  oauth_provider_id VARCHAR(255) NULL,
  date_of_birth DATE NULL,
  gender VARCHAR(32) NULL,
  address_line1 TEXT NULL,
  address_line2 TEXT NULL,
  city VARCHAR(255) NULL,
  state VARCHAR(255) NULL,
  pin_code VARCHAR(32) NULL,
  employment_type VARCHAR(64) NULL,
  employer_name VARCHAR(255) NULL,
  annual_income DECIMAL(15, 2) NULL,
  bank_name VARCHAR(255) NULL,
  account_name VARCHAR(255) NULL,
  registration_status VARCHAR(32) NOT NULL DEFAULT 'pending',
  rejection_reason TEXT NULL,
  reviewed_by CHAR(36) NULL,
  reviewed_at DATETIME(3) NULL,
  approved_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_reg_status (registration_status),
  KEY idx_reg_email (email)
);
