-- Indian states (28) and union territories (8) — reference data for dropdowns.
-- Idempotent: safe to re-run if state_name already exists (INSERT IGNORE).

INSERT INTO indian_states (id, state_name, is_active) VALUES
(gen_random_uuid(), 'Andhra Pradesh', 1),
(gen_random_uuid(), 'Arunachal Pradesh', 1),
(gen_random_uuid(), 'Assam', 1),
(gen_random_uuid(), 'Bihar', 1),
(gen_random_uuid(), 'Chhattisgarh', 1),
(gen_random_uuid(), 'Goa', 1),
(gen_random_uuid(), 'Gujarat', 1),
(gen_random_uuid(), 'Haryana', 1),
(gen_random_uuid(), 'Himachal Pradesh', 1),
(gen_random_uuid(), 'Jharkhand', 1),
(gen_random_uuid(), 'Karnataka', 1),
(gen_random_uuid(), 'Kerala', 1),
(gen_random_uuid(), 'Madhya Pradesh', 1),
(gen_random_uuid(), 'Maharashtra', 1),
(gen_random_uuid(), 'Manipur', 1),
(gen_random_uuid(), 'Meghalaya', 1),
(gen_random_uuid(), 'Mizoram', 1),
(gen_random_uuid(), 'Nagaland', 1),
(gen_random_uuid(), 'Odisha', 1),
(gen_random_uuid(), 'Punjab', 1),
(gen_random_uuid(), 'Rajasthan', 1),
(gen_random_uuid(), 'Sikkim', 1),
(gen_random_uuid(), 'Tamil Nadu', 1),
(gen_random_uuid(), 'Telangana', 1),
(gen_random_uuid(), 'Tripura', 1),
(gen_random_uuid(), 'Uttar Pradesh', 1),
(gen_random_uuid(), 'Uttarakhand', 1),
(gen_random_uuid(), 'West Bengal', 1),
(gen_random_uuid(), 'Andaman and Nicobar Islands', 1),
(gen_random_uuid(), 'Chandigarh', 1),
(gen_random_uuid(), 'Dadra and Nagar Haveli and Daman and Diu', 1),
(gen_random_uuid(), 'Delhi', 1),
(gen_random_uuid(), 'Jammu and Kashmir', 1),
(gen_random_uuid(), 'Ladakh', 1),
(gen_random_uuid(), 'Lakshadweep', 1),
(gen_random_uuid(), 'Puducherry', 1)
ON CONFLICT (state_name) DO NOTHING;
