CREATE TABLE IF NOT EXISTS partner_registrations (
  id CHAR(36) NOT NULL PRIMARY KEY,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  address_line1 VARCHAR(512) NULL,
  address_line2 VARCHAR(512) NULL,
  city VARCHAR(128) NULL,
  state VARCHAR(128) NULL,
  pin_code VARCHAR(16) NULL,
  pan_number VARCHAR(16) NULL,
  bank_name VARCHAR(255) NULL,
  account_number VARCHAR(64) NULL,
  branch_address VARCHAR(512) NULL,
  ifsc_code VARCHAR(32) NULL,
  photo_path VARCHAR(512) NULL,
  pan_card_path VARCHAR(512) NULL,
  cancelled_cheque_path VARCHAR(512) NULL,
  address_proof_path VARCHAR(512) NULL,
  registration_status ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  rejection_reason TEXT NULL,
  reviewed_by CHAR(36) NULL,
  reviewed_at TIMESTAMPTZ NULL,
  approved_at TIMESTAMPTZ NULL,
  approved_user_id CHAR(36) NULL,
  assigned_agent_code VARCHAR(64) NULL,
  financial_year VARCHAR(8) NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_partner_registrations_email (email),
  INDEX idx_partner_registrations_status (registration_status),
  INDEX idx_partner_registrations_created (created_at)
) ;
