-- Marketing, analytics (GA / Meta), SEO, and ad campaign tracking (admin-managed)
CREATE TABLE IF NOT EXISTS marketing_settings (
  id VARCHAR(32) NOT NULL DEFAULT 'default',
  ga_measurement_id VARCHAR(32) NULL,
  gtm_container_id VARCHAR(32) NULL,
  ga_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  meta_pixel_id VARCHAR(64) NULL,
  meta_pixel_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  meta_conversions_api_token VARCHAR(512) NULL,
  custom_head_html MEDIUMTEXT NULL,
  custom_body_html MEDIUMTEXT NULL,
  seo_site_name VARCHAR(255) NULL,
  seo_default_title VARCHAR(255) NULL,
  seo_default_description TEXT NULL,
  seo_keywords TEXT NULL,
  seo_og_image VARCHAR(512) NULL,
  seo_twitter_card VARCHAR(32) NULL DEFAULT 'summary_large_image',
  seo_canonical_url VARCHAR(512) NULL,
  seo_robots VARCHAR(128) NULL DEFAULT 'index,follow',
  google_site_verification VARCHAR(128) NULL,
  page_seo_json LONGTEXT NULL,
  ad_campaigns_json LONGTEXT NULL,
  custom_tags_json LONGTEXT NULL,
  updated_by CHAR(36) NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ;

CREATE TABLE IF NOT EXISTS marketing_events (
  id CHAR(36) NOT NULL PRIMARY KEY,
  event_name VARCHAR(128) NOT NULL,
  platform VARCHAR(16) NOT NULL DEFAULT 'web',
  page_path VARCHAR(512) NULL,
  utm_source VARCHAR(128) NULL,
  utm_medium VARCHAR(128) NULL,
  utm_campaign VARCHAR(128) NULL,
  utm_content VARCHAR(128) NULL,
  utm_term VARCHAR(128) NULL,
  campaign_id VARCHAR(64) NULL,
  payload_json JSON NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_marketing_events_created (created_at),
  INDEX idx_marketing_events_campaign (utm_campaign),
  INDEX idx_marketing_events_name (event_name)
) ;
