CREATE TABLE IF NOT EXISTS credit_cards (
  id CHAR(36) NOT NULL PRIMARY KEY,
  bank_id CHAR(36) NULL,
  bank_name VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(128) NULL,
  description TEXT NULL,
  logo_url TEXT NULL,
  card_network VARCHAR(64) NULL,
  annual_fee DECIMAL(12, 2) NULL,
  joining_fee DECIMAL(12, 2) NULL,
  interest_rate DECIMAL(6, 2) NULL,
  late_payment_fee VARCHAR(128) NULL,
  other_charges TEXT NULL,
  features JSON NULL,
  advantages JSON NULL,
  benefits JSON NULL,
  apply_url TEXT NULL,
  display_priority INT NOT NULL DEFAULT 0,
  status ENUM('active', 'inactive') NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_credit_cards_status (status),
  INDEX idx_credit_cards_bank (bank_id),
  INDEX idx_credit_cards_priority (display_priority)
) ;
